"""
generate_report.py
Generates a formatted Word document report from comparison results.
"""
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from datetime import datetime
import io


def set_cell_bg(cell, hex_color: str):
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), hex_color)
    tcPr.append(shd)


def add_heading(doc, text: str, level: int = 1, color: str = "1F3864"):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = p.add_run(text)
    run.bold = True
    run.font.color.rgb = RGBColor.from_string(color)
    run.font.size = Pt(16 if level == 1 else 13 if level == 2 else 11)
    run.font.name = 'Arial'
    p.space_before = Pt(14)
    p.space_after = Pt(6)
    return p


def add_body(doc, text: str, italic: bool = False):
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(10)
    run.font.name = 'Arial'
    run.italic = italic
    p.space_after = Pt(4)
    return p


def add_finding_table(doc, items, category: str, icon: str, header_color: str, icon_color: str = "FFFFFF"):
    if not items:
        add_body(doc, f"No {category} detected.", italic=True)
        return

    for i, item in enumerate(items):
        desc       = item.description if hasattr(item, 'description') else item.get('description', '')
        sources    = item.sources if hasattr(item, 'sources') else item.get('sources', [])
        confidence = item.confidence if hasattr(item, 'confidence') else item.get('confidence', 0.8)

        table = doc.add_table(rows=1, cols=1)
        table.style = 'Table Grid'

        # Header row
        header_row = table.rows[0]
        hdr_cell   = header_row.cells[0]
        set_cell_bg(hdr_cell, header_color)
        hdr_p   = hdr_cell.paragraphs[0]
        hdr_run = hdr_p.add_run(f"  {icon}  {category} #{i+1}   |   Confidence: {int(float(confidence)*100)}%")
        hdr_run.bold       = True
        hdr_run.font.color.rgb = RGBColor.from_string(icon_color)
        hdr_run.font.size  = Pt(10)
        hdr_run.font.name  = 'Arial'

        # Description row
        desc_row  = table.add_row()
        desc_cell = desc_row.cells[0]
        desc_p    = desc_cell.paragraphs[0]
        desc_run  = desc_p.add_run(desc)
        desc_run.font.size = Pt(10)
        desc_run.font.name = 'Arial'
        desc_cell._tc.get_or_add_tcPr()

        # Sources row
        if sources:
            src_row  = table.add_row()
            src_cell = src_row.cells[0]
            set_cell_bg(src_cell, "F0F4F8")
            src_p   = src_cell.paragraphs[0]
            src_run = src_p.add_run("Sources:  " + "   |   ".join(str(s)[:80] for s in sources))
            src_run.font.size    = Pt(9)
            src_run.font.name    = 'Arial'
            src_run.font.color.rgb = RGBColor.from_string("555555")
            src_run.italic       = True

        doc.add_paragraph().space_after = Pt(4)


def generate_comparison_report(
    result,
    paper_metadata: dict,
    user_query: str,
    processing_time: float,
) -> bytes:
    """
    Generate a Word document report from comparison results.
    Returns bytes that can be downloaded via Streamlit.
    """
    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin   = Inches(1.0)
        section.right_margin  = Inches(1.0)

    # ── COVER ─────────────────────────────────────────────────────────────────
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_p.add_run("Scientific Paper Comparison Report")
    title_run.bold            = True
    title_run.font.size       = Pt(22)
    title_run.font.color.rgb  = RGBColor.from_string("1F3864")
    title_run.font.name       = 'Arial'

    sub_p = doc.add_paragraph()
    sub_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = sub_p.add_run("Generated by Scientific Paper Comparison Engine")
    sub_run.font.size      = Pt(11)
    sub_run.font.color.rgb = RGBColor.from_string("2E75B6")
    sub_run.font.name      = 'Arial'

    date_p = doc.add_paragraph()
    date_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_run = date_p.add_run(f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}")
    date_run.font.size      = Pt(10)
    date_run.font.color.rgb = RGBColor.from_string("888888")
    date_run.font.name      = 'Arial'

    doc.add_paragraph()
    doc.add_paragraph()

    # ── EXECUTIVE SUMMARY ─────────────────────────────────────────────────────
    add_heading(doc, "Executive Summary", 1)

    agreements  = result.agreements if hasattr(result, 'agreements') else result.get('agreements', [])
    contradict  = result.contradictions if hasattr(result, 'contradictions') else result.get('contradictions', [])
    methods     = result.methodology_differences if hasattr(result, 'methodology_differences') else result.get('methodology_differences', [])
    gaps        = result.research_gaps if hasattr(result, 'research_gaps') else result.get('research_gaps', [])

    summary_text = (
        f"This report presents a structured comparison of {len(paper_metadata)} research papers "
        f"analysed using a Multi-Document Retrieval-Augmented Generation (RAG) pipeline powered by "
        f"AWS Bedrock Claude and Amazon Titan Embeddings. The analysis identified "
        f"{len(agreements)} agreements, {len(contradict)} contradictions, "
        f"{len(methods)} methodology differences, and {len(gaps)} research gaps "
        f"across the uploaded papers. Total processing time: {processing_time:.1f} seconds."
    )
    add_body(doc, summary_text)

    doc.add_paragraph()

    # ── QUERY ─────────────────────────────────────────────────────────────────
    add_heading(doc, "Comparison Query", 2, "2E75B6")
    add_body(doc, user_query, italic=True)

    doc.add_paragraph()

    # ── PAPERS ANALYSED ───────────────────────────────────────────────────────
    add_heading(doc, "Papers Analysed", 1)

    table = doc.add_table(rows=1, cols=4)
    table.style = 'Table Grid'

    hdr_cells = table.rows[0].cells
    for cell, text in zip(hdr_cells, ['#', 'Title', 'Filename', 'Chunks']):
        set_cell_bg(cell, "1F3864")
        p   = cell.paragraphs[0]
        run = p.add_run(text)
        run.bold            = True
        run.font.color.rgb  = RGBColor.from_string("FFFFFF")
        run.font.size       = Pt(10)
        run.font.name       = 'Arial'

    for i, (pid, meta) in enumerate(paper_metadata.items()):
        row   = table.add_row()
        cells = row.cells
        bg    = "EBF3FB" if i % 2 == 0 else "FFFFFF"
        for cell in cells:
            set_cell_bg(cell, bg)

        data = [
            str(i + 1),
            meta.get('title', 'Unknown')[:60],
            meta.get('filename', '')[:40],
            str(meta.get('chunks', 0)),
        ]
        for cell, text in zip(cells, data):
            p   = cell.paragraphs[0]
            run = p.add_run(text)
            run.font.size = Pt(9)
            run.font.name = 'Arial'

    doc.add_paragraph()

    # ── RESULTS SUMMARY TABLE ─────────────────────────────────────────────────
    add_heading(doc, "Results Summary", 1)

    sum_table = doc.add_table(rows=1, cols=4)
    sum_table.style = 'Table Grid'

    categories = [
        ("Agreements",            len(agreements), "22c55e"),
        ("Contradictions",        len(contradict), "ef4444"),
        ("Methodology Diffs",     len(methods),    "f59e0b"),
        ("Research Gaps",         len(gaps),       "7c3aed"),
    ]

    for cell, (label, count, color) in zip(sum_table.rows[0].cells, categories):
        set_cell_bg(cell, color)
        p   = cell.paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        num_run = p.add_run(f"{count}\n")
        num_run.bold            = True
        num_run.font.size       = Pt(20)
        num_run.font.color.rgb  = RGBColor.from_string("FFFFFF")
        num_run.font.name       = 'Arial'
        lbl_run = p.add_run(label)
        lbl_run.font.size       = Pt(9)
        lbl_run.font.color.rgb  = RGBColor.from_string("FFFFFF")
        lbl_run.font.name       = 'Arial'

    doc.add_paragraph()

    # ── AGREEMENTS ────────────────────────────────────────────────────────────
    add_heading(doc, "1. Agreements", 1, "166534")
    add_body(doc, "Findings and claims that multiple papers agree upon.", italic=True)
    doc.add_paragraph()
    add_finding_table(doc, agreements, "Agreement", "✓", "166534")

    # ── CONTRADICTIONS ────────────────────────────────────────────────────────
    add_heading(doc, "2. Contradictions", 1, "991B1B")
    add_body(doc, "Areas where papers present conflicting findings or claims.", italic=True)
    doc.add_paragraph()
    add_finding_table(doc, contradict, "Contradiction", "!", "991B1B")

    # ── METHODOLOGY ───────────────────────────────────────────────────────────
    add_heading(doc, "3. Methodology Differences", 1, "92400E")
    add_body(doc, "Differences in research approaches, datasets, and evaluation methods.", italic=True)
    doc.add_paragraph()
    add_finding_table(doc, methods, "Method Diff", "~", "92400E")

    # ── RESEARCH GAPS ─────────────────────────────────────────────────────────
    add_heading(doc, "4. Research Gaps", 1, "4C1D95")
    add_body(doc, "Open questions, limitations, and future work identified.", italic=True)
    doc.add_paragraph()
    add_finding_table(doc, gaps, "Research Gap", "?", "4C1D95")

    # ── FOOTER NOTE ───────────────────────────────────────────────────────────
    doc.add_paragraph()
    footer_p   = doc.add_paragraph()
    footer_run = footer_p.add_run(
        "Generated by Scientific Paper Comparison Engine | "
        "AWS Bedrock Claude | Amazon Titan Embeddings | Pinecone | LangChain | "
        "Ulster University COM748"
    )
    footer_run.font.size      = Pt(8)
    footer_run.font.color.rgb = RGBColor.from_string("AAAAAA")
    footer_run.font.name      = 'Arial'
    footer_p.alignment        = WD_ALIGN_PARAGRAPH.CENTER

    # Save to bytes
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
